### ISSUE TITLE
Missing crystal

### ISSUE THREAD

**Issue by Zumochi** [Shadowtrance/BDO-Gear-Calculator#5]
There's at least one crystal missing from the database. I'd make a pull request for it but I don't know the item ID...

It's the one identical to `Black Magic Crystal - Carmae` except with cast speed: `Black Magic Crystal - Addis`.

Great tool btw!

**Comment by Ihellmasker** [comment]
Thanks for that, guess it got missed! If you spot any others that are missing let us know. I'll get that added in the next update.

**Comment by Shadowtrance** [comment]
Yeah there could be others missing which I've just missed, OR i intentionally left them out as they don't exist anywhere in any region to my knowledge (i play NA and KR and have played JP too).
There's ALOT in the database to go through and I'm only one person. haha So things will no doubt possibly me missed. :)
